"""IMETA: Deterministic, Lossless Image Serialization System."""

from imeta.core import (
    CompressionID,
    CorruptedFileError,
    FormatID,
    HeaderFlags,
    IMETAContainer,
    IMETAError,
    ImageParseResult,
    IntegrityError,
    MAJOR_VERSION,
    MINOR_VERSION,
    SecurityLimitError,
    UnsupportedFormatError,
    ValidationError,
    ValidationReport,
    VersionIncompatibilityError,
    compute_file_sha256_hex,
    compute_sha256_hex,
    decode_file,
    deserialize_imeta,
    encode_file,
    parse_image_bytes,
    parse_image_file,
    serialize_imeta,
    validate_container,
)

__version__ = "1.0.0"

__all__ = [
    "encode_file",
    "decode_file",
    "serialize_imeta",
    "deserialize_imeta",
    "validate_container",
    "parse_image_bytes",
    "parse_image_file",
    "compute_sha256_hex",
    "compute_file_sha256_hex",
    "IMETAContainer",
    "ValidationReport",
    "ImageParseResult",
    "FormatID",
    "CompressionID",
    "HeaderFlags",
    "MAJOR_VERSION",
    "MINOR_VERSION",
    "IMETAError",
    "ValidationError",
    "CorruptedFileError",
    "IntegrityError",
    "UnsupportedFormatError",
    "VersionIncompatibilityError",
    "SecurityLimitError",
]
